import { generateColors, ColorsMap, ThemeConfig } from "./colors";

/**
 * Convert hex color to rgb() format for React Native
 * Example: "#FF5733" -> "rgb(255, 87, 51)"
 */
function hexToRgb(hex: string): string {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    if (!result) return "rgb(0, 0, 0)";
    return `rgb(${Number.parseInt(result[1], 16)}, ${Number.parseInt(result[2], 16)}, ${Number.parseInt(result[3], 16)})`;
}

/**
 * Convert kebab-case to camelCase
 */
function toCamelCase(str: string): string {
    return str.replace(/-([a-z])/g, (_: string, letter: string) => letter.toUpperCase());
}

/**
 * Options for generating NativeWind colors TypeScript file
 */
export interface NativeWindColorsOptions {
    colors: ColorsMap;
    scheme?: string;
    contrast?: number;
}

/**
 * Generate NativeWind-compatible TypeScript colors file
 */
export function generateNativeWindColors(options: NativeWindColorsOptions): string {
    const {
        colors: colorsMap,
        scheme = "content",
        contrast = 0,
    } = options;

    const themeConfig: ThemeConfig = { scheme, contrast };
    const lightColors = generateColors(colorsMap, themeConfig, false, true);
    const darkColors = generateColors(colorsMap, themeConfig, true, true);

    let ts = `/**
 * Material 3 colors for NativeWind
 * Generated by m3-tailwind-colors
 */

export const COLORS = {
  light: {
`;

    Object.entries(lightColors).forEach(([name, hex]) => {
        const camelName = toCamelCase(name);
        ts += `    ${camelName}: '${hexToRgb(hex)}',\n`;
    });

    ts += `  },
  dark: {
`;

    Object.entries(darkColors).forEach(([name, hex]) => {
        const camelName = toCamelCase(name);
        ts += `    ${camelName}: '${hexToRgb(hex)}',\n`;
    });

    ts += `  },
} as const;

export type ColorScheme = keyof typeof COLORS;
export type ColorName = keyof typeof COLORS.light;
`;

    return ts;
}
